# Generated by Django 4.1 on 2022-10-14 12:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootWare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(main.models.Product, models.Model),
        ),
        migrations.CreateModel(
            name='Goggles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(main.models.Product, models.Model),
        ),
        migrations.CreateModel(
            name='KidsWare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(main.models.Product, models.Model),
        ),
        migrations.CreateModel(
            name='MenWare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(main.models.Product, models.Model),
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(main.models.Product, models.Model),
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(main.models.Product, models.Model),
        ),
        migrations.CreateModel(
            name='WomensWare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(main.models.Product, models.Model),
        ),
    ]
